// ignore_for_file: lines_longer_than_80_chars
/// Demo questions loaded from Trails exams JSON files.
/// Used as fallback when API is unavailable.
class DemoQuestions {
  DemoQuestions._();

  // ─── Arabic ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> arabic = [
    {
      '_id': 'ara_001',
      'questionText':
          'ما إعراب كلمة \'الطالب\' في جملة: \'حضر الطالبُ الاجتماع\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'فاعل مرفوع'},
        {'key': 'b', 'value': 'مبتدأ مرفوع'},
        {'key': 'c', 'value': 'مفعول به منصوب'},
        {'key': 'd', 'value': 'خبر مرفوع'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_002',
      'questionText': 'ما نوع الخبر في جملة: \'المعلمُ حاضرٌ\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'خبر مفرد'},
        {'key': 'b', 'value': 'خبر جملة'},
        {'key': 'c', 'value': 'خبر شبه جملة'},
        {'key': 'd', 'value': 'خبر منصوب'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_003',
      'questionText': 'أي من التالي يعتبر حرف عطف؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'في'},
        {'key': 'b', 'value': 'على'},
        {'key': 'c', 'value': 'ثم'},
        {'key': 'd', 'value': 'إلى'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_004',
      'questionText': 'ما علامة رفع الفاعل في جملة: \'جاء المعلمون\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الضمة'},
        {'key': 'b', 'value': 'الواو'},
        {'key': 'c', 'value': 'الألف'},
        {'key': 'd', 'value': 'الياء'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_005',
      'questionText': 'ما اسم الآلة الذي يدل على أداة الحفر؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'حفّارة'},
        {'key': 'b', 'value': 'محفار'},
        {'key': 'c', 'value': 'حفير'},
        {'key': 'd', 'value': 'حفر'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_006',
      'questionText': 'أي من التالي هو من أسماء الإشارة للقريب؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'ذاك'},
        {'key': 'b', 'value': 'ذلك'},
        {'key': 'c', 'value': 'هذا'},
        {'key': 'd', 'value': 'تلك'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_007',
      'questionText': 'ما معنى كلمة \'البأساء\' في القرآن؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الشدة والضراء'},
        {'key': 'b', 'value': 'الرخاء والنعيم'},
        {'key': 'c', 'value': 'القوة والعزة'},
        {'key': 'd', 'value': 'الجود والكرم'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_008',
      'questionText': 'ما نوع الجملة: \'الشمس مشرقة\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'جملة اسمية'},
        {'key': 'b', 'value': 'جملة فعلية'},
        {'key': 'c', 'value': 'جملة شبه اسمية'},
        {'key': 'd', 'value': 'جملة شرطية'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_009',
      'questionText': 'من هو صاحب كتاب \'البيان والتبيين\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الجاحظ'},
        {'key': 'b', 'value': 'المتنبي'},
        {'key': 'c', 'value': 'ابن الأثير'},
        {'key': 'd', 'value': 'الفراهيدي'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_010',
      'questionText': 'ما إعراب \'محمدًا\' في جملة: \'رأيت محمدًا\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'مفعول به منصوب'},
        {'key': 'b', 'value': 'فاعل مرفوع'},
        {'key': 'c', 'value': 'مبتدأ مرفوع'},
        {'key': 'd', 'value': 'خبر منصوب'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_011',
      'questionText': 'أي من التالي ليس من حروف المعاني؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'في'},
        {'key': 'b', 'value': 'لم'},
        {'key': 'c', 'value': 'هل'},
        {'key': 'd', 'value': 'كتاب'},
      ],
      'correctAnswer': 'd',
      'difficulty': 2,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_012',
      'questionText': 'ما جمع كلمة \'قلم\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'أقلام'},
        {'key': 'b', 'value': 'قلمون'},
        {'key': 'c', 'value': 'أقالم'},
        {'key': 'd', 'value': 'قلوم'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_013',
      'questionText': 'في أي سورة وردت قصة أصحاب الكهف؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الكهف'},
        {'key': 'b', 'value': 'البقرة'},
        {'key': 'c', 'value': 'آل عمران'},
        {'key': 'd', 'value': 'النمل'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_014',
      'questionText': 'ما معنى كلمة \'الزكاة\' لغةً؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الزيادة والنماء'},
        {'key': 'b', 'value': 'النقصان'},
        {'key': 'c', 'value': 'الطهارة'},
        {'key': 'd', 'value': 'الزينة'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_015',
      'questionText': 'أي من التالي يعتبر فعلاً ناقصاً من أفعال كان وأخواتها؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'أصبح'},
        {'key': 'b', 'value': 'ذهب'},
        {'key': 'c', 'value': 'جاء'},
        {'key': 'd', 'value': 'نزل'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_016',
      'questionText':
          'ما نوع الاستفهام في قوله تعالى: \'هل أتاك حديث الغاشية؟\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'استفهام تقريري'},
        {'key': 'b', 'value': 'استفهام إنكاري'},
        {'key': 'c', 'value': 'استفهام توبيخي'},
        {'key': 'd', 'value': 'استفهام تعجبي'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_017',
      'questionText': 'كم عدد حروف الهجاء العربية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '28'},
        {'key': 'b', 'value': '26'},
        {'key': 'c', 'value': '29'},
        {'key': 'd', 'value': '30'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_018',
      'questionText': 'ما علامة جر الاسم في جملة: \'مررت بالرجلِ الكريم\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الكسرة'},
        {'key': 'b', 'value': 'الفتحة'},
        {'key': 'c', 'value': 'الضمة'},
        {'key': 'd', 'value': 'السكون'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_019',
      'questionText': 'أي من التالي يعتبر من المحسنات البديعية اللفظية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الجناس'},
        {'key': 'b', 'value': 'التشبيه'},
        {'key': 'c', 'value': 'الاستعارة'},
        {'key': 'd', 'value': 'الكناية'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Arabic',
    },
    {
      '_id': 'ara_020',
      'questionText': 'ما إعراب كلمة \'السماء\' في جملة: \'السماءُ صافيةٌ\'؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'مبتدأ مرفوع'},
        {'key': 'b', 'value': 'فاعل مرفوع'},
        {'key': 'c', 'value': 'خبر مرفوع'},
        {'key': 'd', 'value': 'مفعول به منصوب'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Arabic',
    },
  ];

  // ─── English ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> english = [
    {
      '_id': 'eng_001',
      'questionText':
          'Choose the correct verb: \'She ______ to school every day.\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'go'},
        {'key': 'b', 'value': 'goes'},
        {'key': 'c', 'value': 'going'},
        {'key': 'd', 'value': 'went'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_002',
      'questionText': 'What is the plural of \'child\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'childs'},
        {'key': 'b', 'value': 'children'},
        {'key': 'c', 'value': 'childrens'},
        {'key': 'd', 'value': 'childes'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_003',
      'questionText': 'Which word is an adjective?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'run'},
        {'key': 'b', 'value': 'beautiful'},
        {'key': 'c', 'value': 'quickly'},
        {'key': 'd', 'value': 'the'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_004',
      'questionText': 'What is the synonym of \'happy\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'sad'},
        {'key': 'b', 'value': 'joyful'},
        {'key': 'c', 'value': 'angry'},
        {'key': 'd', 'value': 'tired'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_005',
      'questionText': 'Which sentence is in the past tense?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'I eat'},
        {'key': 'b', 'value': 'I am eating'},
        {'key': 'c', 'value': 'I ate'},
        {'key': 'd', 'value': 'I will eat'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_006',
      'questionText':
          'What is the object in the sentence: \'The boy kicked the ball\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'The boy'},
        {'key': 'b', 'value': 'kicked'},
        {'key': 'c', 'value': 'the ball'},
        {'key': 'd', 'value': 'boy'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_007',
      'questionText':
          'Choose the correct preposition: \'I am interested ______ learning Arabic.\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'in'},
        {'key': 'b', 'value': 'on'},
        {'key': 'c', 'value': 'at'},
        {'key': 'd', 'value': 'for'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_008',
      'questionText': 'What is the antonym of \'difficult\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'hard'},
        {'key': 'b', 'value': 'easy'},
        {'key': 'c', 'value': 'tough'},
        {'key': 'd', 'value': 'complex'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_009',
      'questionText': 'Which of the following is a conjunction?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'and'},
        {'key': 'b', 'value': 'the'},
        {'key': 'c', 'value': 'to'},
        {'key': 'd', 'value': 'in'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_010',
      'questionText': 'What is the comparative form of \'good\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'gooder'},
        {'key': 'b', 'value': 'better'},
        {'key': 'c', 'value': 'best'},
        {'key': 'd', 'value': 'most good'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_011',
      'questionText':
          'Identify the adverb in: \'He ran quickly to catch the bus.\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'He'},
        {'key': 'b', 'value': 'ran'},
        {'key': 'c', 'value': 'quickly'},
        {'key': 'd', 'value': 'bus'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_012',
      'questionText':
          'What is the passive voice of \'The chef cooked dinner\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'Dinner is cooked'},
        {'key': 'b', 'value': 'Dinner was cooked'},
        {'key': 'c', 'value': 'Dinner cooked'},
        {'key': 'd', 'value': 'Dinner is being cooked'},
      ],
      'correctAnswer': 'b',
      'difficulty': 3,
      'subject': 'English',
    },
    {
      '_id': 'eng_013',
      'questionText': 'Choose the correct spelling:',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'accomodate'},
        {'key': 'b', 'value': 'accommodate'},
        {'key': 'c', 'value': 'acommodate'},
        {'key': 'd', 'value': 'acommodate'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_014',
      'questionText': 'What does \'benevolent\' mean?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'kind'},
        {'key': 'b', 'value': 'mean'},
        {'key': 'c', 'value': 'rich'},
        {'key': 'd', 'value': 'poor'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'English',
    },
    {
      '_id': 'eng_015',
      'questionText': 'Which tense is used for actions happening now?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'present simple'},
        {'key': 'b', 'value': 'present continuous'},
        {'key': 'c', 'value': 'past simple'},
        {'key': 'd', 'value': 'future simple'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
    {
      '_id': 'eng_016',
      'questionText':
          'What is the subject in: \'The beautiful flowers bloom in spring\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'beautiful'},
        {'key': 'b', 'value': 'flowers'},
        {'key': 'c', 'value': 'bloom'},
        {'key': 'd', 'value': 'spring'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_017',
      'questionText': 'Choose the correct pronoun: \'This cake is ______.\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'me'},
        {'key': 'b', 'value': 'my'},
        {'key': 'c', 'value': 'mine'},
        {'key': 'd', 'value': 'I'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_018',
      'questionText': 'What is the opposite of \'ancient\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'old'},
        {'key': 'b', 'value': 'new'},
        {'key': 'c', 'value': 'modern'},
        {'key': 'd', 'value': 'young'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_019',
      'questionText': 'Identify the error: \'She don\'t like coffee.\'',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'She'},
        {'key': 'b', 'value': 'don\'t'},
        {'key': 'c', 'value': 'like'},
        {'key': 'd', 'value': 'coffee'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'English',
    },
    {
      '_id': 'eng_020',
      'questionText': 'What is the third form of \'write\'?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'wrote'},
        {'key': 'b', 'value': 'written'},
        {'key': 'c', 'value': 'writing'},
        {'key': 'd', 'value': 'write'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'English',
    },
  ];

  // ─── Mathematics ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> mathematics = [
    {
      '_id': 'math_001',
      'questionText': 'What is the value of 5 + 3 × 2?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '16'},
        {'key': 'b', 'value': '11'},
        {'key': 'c', 'value': '10'},
        {'key': 'd', 'value': '13'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_002',
      'questionText': 'What is 7²?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '14'},
        {'key': 'b', 'value': '49'},
        {'key': 'c', 'value': '7'},
        {'key': 'd', 'value': '21'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_003',
      'questionText': 'Solve for x: x + 5 = 12',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '5'},
        {'key': 'b', 'value': '6'},
        {'key': 'c', 'value': '7'},
        {'key': 'd', 'value': '8'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_004',
      'questionText':
          'What is the area of a rectangle with length 8 and width 3?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '11'},
        {'key': 'b', 'value': '24'},
        {'key': 'c', 'value': '16'},
        {'key': 'd', 'value': '32'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_005',
      'questionText': 'What is 25% of 200?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '25'},
        {'key': 'b', 'value': '50'},
        {'key': 'c', 'value': '75'},
        {'key': 'd', 'value': '100'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_006',
      'questionText': 'What is the perimeter of a square with side 6?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '12'},
        {'key': 'b', 'value': '24'},
        {'key': 'c', 'value': '36'},
        {'key': 'd', 'value': '18'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_007',
      'questionText': 'Which of these is a prime number?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '4'},
        {'key': 'b', 'value': '9'},
        {'key': 'c', 'value': '11'},
        {'key': 'd', 'value': '15'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_008',
      'questionText': 'What is 8 ÷ 2 × (2 + 2)?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1'},
        {'key': 'b', 'value': '8'},
        {'key': 'c', 'value': '16'},
        {'key': 'd', 'value': '4'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_009',
      'questionText': 'What is the volume of a cube with side 3?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '9'},
        {'key': 'b', 'value': '18'},
        {'key': 'c', 'value': '27'},
        {'key': 'd', 'value': '36'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_010',
      'questionText':
          'What is the slope of a line with points (0,0) and (2,4)?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1'},
        {'key': 'b', 'value': '2'},
        {'key': 'c', 'value': '0.5'},
        {'key': 'd', 'value': '4'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_011',
      'questionText': 'What is the square root of 144?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '10'},
        {'key': 'b', 'value': '11'},
        {'key': 'c', 'value': '12'},
        {'key': 'd', 'value': '13'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_012',
      'questionText': 'What is the median of 3, 7, 8, 10, 12?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '7'},
        {'key': 'b', 'value': '8'},
        {'key': 'c', 'value': '9'},
        {'key': 'd', 'value': '10'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_013',
      'questionText':
          'What is the probability of rolling an even number on a dice?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1/2'},
        {'key': 'b', 'value': '1/3'},
        {'key': 'c', 'value': '1/4'},
        {'key': 'd', 'value': '2/3'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_014',
      'questionText': 'What is the sum of angles in a triangle?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '90°'},
        {'key': 'b', 'value': '180°'},
        {'key': 'c', 'value': '270°'},
        {'key': 'd', 'value': '360°'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_015',
      'questionText': 'If y = 2x + 3, find y when x = 4.',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '8'},
        {'key': 'b', 'value': '11'},
        {'key': 'c', 'value': '9'},
        {'key': 'd', 'value': '12'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_016',
      'questionText': 'How many edges does a cube have?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '6'},
        {'key': 'b', 'value': '8'},
        {'key': 'c', 'value': '10'},
        {'key': 'd', 'value': '12'},
      ],
      'correctAnswer': 'd',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_017',
      'questionText': 'What is the distance between -5 and 3 on a number line?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '2'},
        {'key': 'b', 'value': '5'},
        {'key': 'c', 'value': '8'},
        {'key': 'd', 'value': '3'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_018',
      'questionText': 'What is the LCM of 6 and 8?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '12'},
        {'key': 'b', 'value': '24'},
        {'key': 'c', 'value': '48'},
        {'key': 'd', 'value': '16'},
      ],
      'correctAnswer': 'b',
      'difficulty': 3,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_019',
      'questionText': 'What is 1/2 + 1/3?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '2/5'},
        {'key': 'b', 'value': '5/6'},
        {'key': 'c', 'value': '1/6'},
        {'key': 'd', 'value': '2/6'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Mathematics',
    },
    {
      '_id': 'math_020',
      'questionText': 'What is the derivative of x²?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'x'},
        {'key': 'b', 'value': '2x'},
        {'key': 'c', 'value': 'x²'},
        {'key': 'd', 'value': '2x²'},
      ],
      'correctAnswer': 'b',
      'difficulty': 3,
      'subject': 'Mathematics',
    },
  ];

  // ─── History ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> history = [
    {
      '_id': 'his_001',
      'questionText': 'من هو مؤسس الدولة الأموية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'عثمان بن عفان'},
        {'key': 'b', 'value': 'معاوية بن أبي سفيان'},
        {'key': 'c', 'value': 'علي بن أبي طالب'},
        {'key': 'd', 'value': 'الحسن بن علي'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'History',
    },
    {
      '_id': 'his_002',
      'questionText': 'في أي عام حدثت معركة حطين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1187'},
        {'key': 'b', 'value': '1099'},
        {'key': 'c', 'value': '1147'},
        {'key': 'd', 'value': '1190'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_003',
      'questionText': 'من هو القائد الذي فتح القسطنطينية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'صلاح الدين الأيوبي'},
        {'key': 'b', 'value': 'محمد الفاتح'},
        {'key': 'c', 'value': 'هارون الرشيد'},
        {'key': 'd', 'value': 'المأمون'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_004',
      'questionText': 'ما هي أطول حضارة في التاريخ؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الرومانية'},
        {'key': 'b', 'value': 'المصرية القديمة'},
        {'key': 'c', 'value': 'اليونانية'},
        {'key': 'd', 'value': 'الفارسية'},
      ],
      'correctAnswer': 'b',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_005',
      'questionText': 'من هو النبي الذي بنى الكعبة مع ابنه إسماعيل؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'نوح'},
        {'key': 'b', 'value': 'إبراهيم'},
        {'key': 'c', 'value': 'موسى'},
        {'key': 'd', 'value': 'عيسى'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'History',
    },
    {
      '_id': 'his_006',
      'questionText': 'في أي عام بدأت الحرب العالمية الأولى؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1914'},
        {'key': 'b', 'value': '1918'},
        {'key': 'c', 'value': '1939'},
        {'key': 'd', 'value': '1945'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_007',
      'questionText': 'من هو أول خليفة في الدولة العباسية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'أبو العباس السفاح'},
        {'key': 'b', 'value': 'أبو جعفر المنصور'},
        {'key': 'c', 'value': 'هارون الرشيد'},
        {'key': 'd', 'value': 'المعتصم'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_008',
      'questionText': 'ما اسم المعركة التي هزم فيها المسلمون في الأندلس؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'معركة بلاط الشهداء'},
        {'key': 'b', 'value': 'معركة وادي لكة'},
        {'key': 'c', 'value': 'معركة القادسية'},
        {'key': 'd', 'value': 'معركة اليرموك'},
      ],
      'correctAnswer': 'b',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_009',
      'questionText': 'من هو صاحب نظرية التطور؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'نيوتن'},
        {'key': 'b', 'value': 'داروين'},
        {'key': 'c', 'value': 'أينشتاين'},
        {'key': 'd', 'value': 'غاليليو'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_010',
      'questionText': 'ما هي عاصمة الدولة الأيوبية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'دمشق'},
        {'key': 'b', 'value': 'القاهرة'},
        {'key': 'c', 'value': 'بغداد'},
        {'key': 'd', 'value': 'القدس'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_011',
      'questionText': 'متى تم فتح مكة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '8 هـ'},
        {'key': 'b', 'value': '9 هـ'},
        {'key': 'c', 'value': '10 هـ'},
        {'key': 'd', 'value': '7 هـ'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'History',
    },
    {
      '_id': 'his_012',
      'questionText': 'من أول من خط بالقلم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'إدريس عليه السلام'},
        {'key': 'b', 'value': 'سليمان عليه السلام'},
        {'key': 'c', 'value': 'داود عليه السلام'},
        {'key': 'd', 'value': 'موسى عليه السلام'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_013',
      'questionText': 'في أي عام سقطت الدولة الأموية في الأندلس؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1492'},
        {'key': 'b', 'value': '711'},
        {'key': 'c', 'value': '1031'},
        {'key': 'd', 'value': '1212'},
      ],
      'correctAnswer': 'c',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_014',
      'questionText': 'من هو أول من وضع علم النحو؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الفراهيدي'},
        {'key': 'b', 'value': 'سيبويه'},
        {'key': 'c', 'value': 'أبو الأسود الدؤلي'},
        {'key': 'd', 'value': 'الكسائي'},
      ],
      'correctAnswer': 'c',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_015',
      'questionText': 'ما هي الدولة التي حكمت مصر بعد الفاطميين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'المماليك'},
        {'key': 'b', 'value': 'الأيوبيون'},
        {'key': 'c', 'value': 'العباسيون'},
        {'key': 'd', 'value': 'العثمانيون'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_016',
      'questionText': 'من هو ثاني الخلفاء الراشدين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'أبو بكر الصديق'},
        {'key': 'b', 'value': 'عمر بن الخطاب'},
        {'key': 'c', 'value': 'عثمان بن عفان'},
        {'key': 'd', 'value': 'علي بن أبي طالب'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'History',
    },
    {
      '_id': 'his_017',
      'questionText': 'في أي سنة تم إنشاء الأمم المتحدة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1945'},
        {'key': 'b', 'value': '1950'},
        {'key': 'c', 'value': '1948'},
        {'key': 'd', 'value': '1939'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'History',
    },
    {
      '_id': 'his_018',
      'questionText': 'من هو أشهر ملوك الدولة المغولية في الهند؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'تيمورلنك'},
        {'key': 'b', 'value': 'ظهير الدين بابر'},
        {'key': 'c', 'value': 'أكبر'},
        {'key': 'd', 'value': 'شاه جهان'},
      ],
      'correctAnswer': 'c',
      'difficulty': 3,
      'subject': 'History',
    },
    {
      '_id': 'his_019',
      'questionText': 'ماذا يطلق على عصر الخلفاء الراشدين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'العصر الذهبي'},
        {'key': 'b', 'value': 'عصر النبوة'},
        {'key': 'c', 'value': 'عصر الخلافة الراشدة'},
        {'key': 'd', 'value': 'عصر الفتنة'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'History',
    },
    {
      '_id': 'his_020',
      'questionText': 'من هو الفرعون الذي عاصر موسى عليه السلام؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'رمسيس الثاني'},
        {'key': 'b', 'value': 'أخناتون'},
        {'key': 'c', 'value': 'توت عنخ آمون'},
        {'key': 'd', 'value': 'خوفو'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'History',
    },
  ];

  // ─── Biology ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> biology = [
    {
      '_id': 'bio_001',
      'questionText': 'ما هي الوحدة الأساسية للحياة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الخلية'},
        {'key': 'b', 'value': 'النسيج'},
        {'key': 'c', 'value': 'العضو'},
        {'key': 'd', 'value': 'الجهاز'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_002',
      'questionText': 'أين تحدث عملية التمثيل الضوئي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الميتوكوندريا'},
        {'key': 'b', 'value': 'البلاستيدات الخضراء'},
        {'key': 'c', 'value': 'النواة'},
        {'key': 'd', 'value': 'الريبوسومات'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_003',
      'questionText': 'كم عدد الكروموسومات في الخلية البشرية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '23'},
        {'key': 'b', 'value': '46'},
        {'key': 'c', 'value': '92'},
        {'key': 'd', 'value': '12'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_004',
      'questionText': 'ما هو العضو المسؤول عن ضخ الدم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الرئة'},
        {'key': 'b', 'value': 'القلب'},
        {'key': 'c', 'value': 'الكبد'},
        {'key': 'd', 'value': 'المعدة'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_005',
      'questionText': 'ما هي مكونات الجهاز العصبي المركزي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الدماغ والحبل الشوكي'},
        {'key': 'b', 'value': 'الأعصاب الطرفية'},
        {'key': 'c', 'value': 'النخاع المستطيل'},
        {'key': 'd', 'value': 'المخيخ'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_006',
      'questionText': 'أين يحدث التنفس الخلوي في الخلية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'النواة'},
        {'key': 'b', 'value': 'الميتوكوندريا'},
        {'key': 'c', 'value': 'السيتوبلازم'},
        {'key': 'd', 'value': 'الغشاء الخلوي'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_007',
      'questionText': 'ما هو المرض الذي يسببه فيروس HIV؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الأيدز'},
        {'key': 'b', 'value': 'السرطان'},
        {'key': 'c', 'value': 'السكري'},
        {'key': 'd', 'value': 'السل'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_008',
      'questionText': 'ما هي وظيفة الكلى؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'تنقية الدم'},
        {'key': 'b', 'value': 'إنتاج الأنسولين'},
        {'key': 'c', 'value': 'هضم الطعام'},
        {'key': 'd', 'value': 'نقل الأكسجين'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_009',
      'questionText': 'ما هو الجين المسؤول عن لون العيون؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الجين السائد'},
        {'key': 'b', 'value': 'الجين المتنحي'},
        {'key': 'c', 'value': 'الجين المصاحب'},
        {'key': 'd', 'value': 'الجين المحايد'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_010',
      'questionText': 'كم عدد أنواع الدم التي يحددها نظام ABO؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '2'},
        {'key': 'b', 'value': '4'},
        {'key': 'c', 'value': '6'},
        {'key': 'd', 'value': '8'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_011',
      'questionText': 'ما هي أصغر وحدة في الجهاز العصبي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'العصبون'},
        {'key': 'b', 'value': 'الخلية الدبقية'},
        {'key': 'c', 'value': 'المشبك'},
        {'key': 'd', 'value': 'المحور'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_012',
      'questionText': 'أين ينتج الأنسولين في الجسم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الكبد'},
        {'key': 'b', 'value': 'البنكرياس'},
        {'key': 'c', 'value': 'المعدة'},
        {'key': 'd', 'value': 'الطحال'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_013',
      'questionText': 'ما هي المادة الوراثية في الكائنات الحية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'RNA'},
        {'key': 'b', 'value': 'DNA'},
        {'key': 'c', 'value': 'ATP'},
        {'key': 'd', 'value': 'NADH'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_014',
      'questionText': 'كم عدد أزواج الكروموسومات في الخلية البشرية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '23'},
        {'key': 'b', 'value': '46'},
        {'key': 'c', 'value': '11'},
        {'key': 'd', 'value': '12'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_015',
      'questionText': 'ما هو هرمون النمو الذي يفرز من الغدة النخامية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'GH'},
        {'key': 'b', 'value': 'TSH'},
        {'key': 'c', 'value': 'ACTH'},
        {'key': 'd', 'value': 'FSH'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_016',
      'questionText': 'أين تتم عملية الهضم الكيميائي للبروتين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الفم'},
        {'key': 'b', 'value': 'المعدة'},
        {'key': 'c', 'value': 'الأمعاء الدقيقة'},
        {'key': 'd', 'value': 'الأمعاء الغليظة'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_017',
      'questionText': 'ما هي وظيفة خلايا الدم الحمراء؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'نقل الأكسجين'},
        {'key': 'b', 'value': 'محاربة العدوى'},
        {'key': 'c', 'value': 'تخثر الدم'},
        {'key': 'd', 'value': 'إنتاج الهرمونات'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_018',
      'questionText':
          'ما اسم العملية التي تحصل فيها الخلية على الطاقة بدون أكسجين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'التخمر'},
        {'key': 'b', 'value': 'التنفس الهوائي'},
        {'key': 'c', 'value': 'البناء الضوئي'},
        {'key': 'd', 'value': 'التحلل المائي'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_019',
      'questionText': 'كيف يسمى انقسام الخلية الجسدية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الانقسام المتساوي'},
        {'key': 'b', 'value': 'الانقسام المنصف'},
        {'key': 'c', 'value': 'الانقسام الفتيلي'},
        {'key': 'd', 'value': 'الانقسام الانتقائي'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Biology',
    },
    {
      '_id': 'bio_020',
      'questionText': 'ما هو الهرمون المسؤول عن تنظيم السكر في الدم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الأنسولين'},
        {'key': 'b', 'value': 'الأدرينالين'},
        {'key': 'c', 'value': 'الكورتيزول'},
        {'key': 'd', 'value': 'الثيروكسين'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Biology',
    },
  ];

  // ─── Chemistry ─────────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> chemistry = [
    {
      '_id': 'chem_001',
      'questionText': 'ما هو رمز عنصر الحديد؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'Fe'},
        {'key': 'b', 'value': 'Cu'},
        {'key': 'c', 'value': 'Ag'},
        {'key': 'd', 'value': 'Au'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_002',
      'questionText': 'أي من التالي يعتبر حمضاً قوياً؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'HCl'},
        {'key': 'b', 'value': 'CH3COOH'},
        {'key': 'c', 'value': 'H2CO3'},
        {'key': 'd', 'value': 'H3PO4'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_003',
      'questionText': 'ما ناتج تفاعل: NaOH + HCl → ?',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'NaCl + H2O'},
        {'key': 'b', 'value': 'NaCl + O2'},
        {'key': 'c', 'value': 'H2O + NaCl2'},
        {'key': 'd', 'value': 'N2O + NaCl'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_004',
      'questionText': 'كم عدد الذرات في جزيء الماء H2O؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '2'},
        {'key': 'b', 'value': '3'},
        {'key': 'c', 'value': '4'},
        {'key': 'd', 'value': '5'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_005',
      'questionText': 'ما هي الصيغة الكيميائية للملح؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'NaCl'},
        {'key': 'b', 'value': 'NaOH'},
        {'key': 'c', 'value': 'Na2CO3'},
        {'key': 'd', 'value': 'NaHCO3'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_006',
      'questionText': 'أين تقع العناصر النبيلة في الجدول الدوري؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'المجموعة 18'},
        {'key': 'b', 'value': 'المجموعة 1'},
        {'key': 'c', 'value': 'المجموعة 7'},
        {'key': 'd', 'value': 'المجموعة 14'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_007',
      'questionText': 'ما الذي يسببه وجود أيونات الهيدروجين في المحلول؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'حمضية'},
        {'key': 'b', 'value': 'قاعدية'},
        {'key': 'c', 'value': 'محايدة'},
        {'key': 'd', 'value': 'مالحة'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_008',
      'questionText': 'ما هو الرقم الهيدروجيني للماء النقي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '7'},
        {'key': 'b', 'value': '0'},
        {'key': 'c', 'value': '14'},
        {'key': 'd', 'value': '1'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_009',
      'questionText': 'ما هي المادة التي تسبب الصدأ؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الأكسجين'},
        {'key': 'b', 'value': 'الهيدروجين'},
        {'key': 'c', 'value': 'النتروجين'},
        {'key': 'd', 'value': 'الكربون'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_010',
      'questionText': 'كم عدد إلكترونات التكافؤ في الكربون؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '4'},
        {'key': 'b', 'value': '2'},
        {'key': 'c', 'value': '6'},
        {'key': 'd', 'value': '8'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_011',
      'questionText': 'ما هو العنصر الأكثر وفرة في الغلاف الجوي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الأكسجين'},
        {'key': 'b', 'value': 'النتروجين'},
        {'key': 'c', 'value': 'الكربون'},
        {'key': 'd', 'value': 'الأرجون'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_012',
      'questionText': 'أي من التالي هو عملية فيزيائية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'ذوبان الثلج'},
        {'key': 'b', 'value': 'صدأ الحديد'},
        {'key': 'c', 'value': 'احتراق الخشب'},
        {'key': 'd', 'value': 'تخمير الخبز'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_013',
      'questionText': 'ما هي الكتلة المولية للماء؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '18 g/mol'},
        {'key': 'b', 'value': '16 g/mol'},
        {'key': 'c', 'value': '20 g/mol'},
        {'key': 'd', 'value': '22 g/mol'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_014',
      'questionText': 'كم عدد النظائر الطبيعية للهيدروجين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '2'},
        {'key': 'b', 'value': '3'},
        {'key': 'c', 'value': '1'},
        {'key': 'd', 'value': '4'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_015',
      'questionText': 'ما هي الصيغة الجزيئية للجلوكوز؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'C6H12O6'},
        {'key': 'b', 'value': 'C6H6O6'},
        {'key': 'c', 'value': 'C12H22O11'},
        {'key': 'd', 'value': 'C5H10O5'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_016',
      'questionText': 'ما هو الغاز الذي يستخدم في إطفاء الحرائق؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'ثاني أكسيد الكربون'},
        {'key': 'b', 'value': 'الأكسجين'},
        {'key': 'c', 'value': 'النيتروجين'},
        {'key': 'd', 'value': 'الهيدروجين'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_017',
      'questionText':
          'أي من التالي يعتبر عاملاً مساعداً في التفاعلات الكيميائية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'المحفز'},
        {'key': 'b', 'value': 'المذيب'},
        {'key': 'c', 'value': 'الضغط'},
        {'key': 'd', 'value': 'الحرارة'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_018',
      'questionText': 'ما هو الرمز الكيميائي للذهب؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'Au'},
        {'key': 'b', 'value': 'Ag'},
        {'key': 'c', 'value': 'Cu'},
        {'key': 'd', 'value': 'Fe'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_019',
      'questionText': 'كم عدد مستويات الطاقة في ذرة الصوديوم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '3'},
        {'key': 'b', 'value': '2'},
        {'key': 'c', 'value': '4'},
        {'key': 'd', 'value': '1'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Chemistry',
    },
    {
      '_id': 'chem_020',
      'questionText': 'ما هي المعادلة الكيميائية لاحتراق الميثان؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'CH4 + 2O2 → CO2 + 2H2O'},
        {'key': 'b', 'value': 'CH4 + O2 → CO2 + H2O'},
        {'key': 'c', 'value': 'CH4 + 3O2 → CO2 + 2H2O'},
        {'key': 'd', 'value': 'CH4 + 2O2 → CO + 2H2O'},
      ],
      'correctAnswer': 'a',
      'difficulty': 3,
      'subject': 'Chemistry',
    },
  ];

  /// All demo questions combined.
  static const List<Map<String, dynamic>> all = [
    ...arabic,
    ...english,
    ...mathematics,
    ...history,
    ...biology,
    ...chemistry,
    ...extraQuestions,
  ];

  /// Extra questions — geography, computer science, critical thinking, general knowledge.
  static const List<Map<String, dynamic>> extraQuestions = [
    {
      '_id': 'extra_001',
      'questionText': 'ما هي عاصمة المملكة العربية السعودية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'جدة'},
        {'key': 'b', 'value': 'الرياض'},
        {'key': 'c', 'value': 'مكة المكرمة'},
        {'key': 'd', 'value': 'الدمام'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الجغرافيا',
    },
    {
      '_id': 'extra_002',
      'questionText': 'ما هو أطول نهر في العالم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'نهر الأمازون'},
        {'key': 'b', 'value': 'نهر النيل'},
        {'key': 'c', 'value': 'نهر المسيسيبي'},
        {'key': 'd', 'value': 'نهر اليانغتسي'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الجغرافيا',
    },
    {
      '_id': 'extra_003',
      'questionText': 'كم عدد قارات العالم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '5'},
        {'key': 'b', 'value': '6'},
        {'key': 'c', 'value': '7'},
        {'key': 'd', 'value': '8'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'الجغرافيا',
    },
    {
      '_id': 'extra_004',
      'questionText': 'ما هي أكبر دولة في العالم من حيث المساحة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الصين'},
        {'key': 'b', 'value': 'الولايات المتحدة'},
        {'key': 'c', 'value': 'كندا'},
        {'key': 'd', 'value': 'روسيا'},
      ],
      'correctAnswer': 'd',
      'difficulty': 1,
      'subject': 'الجغرافيا',
    },
    {
      '_id': 'extra_005',
      'questionText': 'أي من التالي يُعدّ أعلى قمة جبلية في العالم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'جبل كيليمنجارو'},
        {'key': 'b', 'value': 'جبل إيفرست'},
        {'key': 'c', 'value': 'جبل ماكينلي'},
        {'key': 'd', 'value': 'جبل أكونكاغوا'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الجغرافيا',
    },
    {
      '_id': 'extra_006',
      'questionText':
          'ما هو لغة البرمجة المستخدمة أساساً لتطوير تطبيقات Android؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'Swift'},
        {'key': 'b', 'value': 'Python'},
        {'key': 'c', 'value': 'Kotlin'},
        {'key': 'd', 'value': 'C++'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'علوم الحاسب',
    },
    {
      '_id': 'extra_007',
      'questionText': 'ما هو الاختصار الكامل لـ CPU؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'Central Processing Unit'},
        {'key': 'b', 'value': 'Computer Processing Unit'},
        {'key': 'c', 'value': 'Central Program Unit'},
        {'key': 'd', 'value': 'Core Processing Unit'},
      ],
      'correctAnswer': 'a',
      'difficulty': 1,
      'subject': 'علوم الحاسب',
    },
    {
      '_id': 'extra_008',
      'questionText':
          'ما هو نظام الترقيم الثنائي (Binary) الذي يمثل العدد 10 في النظام العشري؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '1010'},
        {'key': 'b', 'value': '1100'},
        {'key': 'c', 'value': '1001'},
        {'key': 'd', 'value': '0110'},
      ],
      'correctAnswer': 'a',
      'difficulty': 2,
      'subject': 'علوم الحاسب',
    },
    {
      '_id': 'extra_009',
      'questionText': 'ما هو الفرق الأساسي بين RAM و ROM؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'RAM أسرع من ROM دائماً'},
        {
          'key': 'b',
          'value': 'RAM مؤقتة وتُفقد عند إيقاف التشغيل، بينما ROM دائمة'
        },
        {'key': 'c', 'value': 'ROM تُستخدم للتخزين المؤقت فقط'},
        {'key': 'd', 'value': 'لا فرق بينهما'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'علوم الحاسب',
    },
    {
      '_id': 'extra_010',
      'questionText': 'ما هو بروتوكول نقل النص التشعبي المستخدم في الويب؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'FTP'},
        {'key': 'b', 'value': 'SMTP'},
        {'key': 'c', 'value': 'HTTP'},
        {'key': 'd', 'value': 'SSH'},
      ],
      'correctAnswer': 'c',
      'difficulty': 1,
      'subject': 'علوم الحاسب',
    },
    {
      '_id': 'extra_011',
      'questionText':
          'إذا كانت جميع الطلاب يحبون الرياضيات، وأحمد طالب، فماذا نستنتج؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'أحمد لا يحب الرياضيات'},
        {'key': 'b', 'value': 'أحمد يحب الرياضيات'},
        {'key': 'c', 'value': 'لا يمكن الاستنتاج'},
        {'key': 'd', 'value': 'أحمد ليس طالباً'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'التفكير النقدي',
    },
    {
      '_id': 'extra_012',
      'questionText': 'أي من التالي يُعدّ مغالطة منطقية؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الاستنتاج من المقدمات الصحيحة'},
        {'key': 'b', 'value': 'الهجوم على شخصية المتحدث بدلاً من حجته'},
        {'key': 'c', 'value': 'تقديم أدلة موثوقة'},
        {'key': 'd', 'value': 'الاستشهاد بمصادر علمية'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'التفكير النقدي',
    },
    {
      '_id': 'extra_013',
      'questionText': 'ما الخطوة الأولى في حل المشكلات بشكل منهجي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'تطبيق الحل مباشرة'},
        {'key': 'b', 'value': 'تحديد المشكلة وفهمها بوضوح'},
        {'key': 'c', 'value': 'جمع كل المعلومات الممكنة'},
        {'key': 'd', 'value': 'تقييم النتائج'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'التفكير النقدي',
    },
    {
      '_id': 'extra_014',
      'questionText': 'أي من التالي يُمثّل تفكيراً نقدياً سليماً؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'قبول المعلومات دون تساؤل'},
        {'key': 'b', 'value': 'رفض كل الأفكار الجديدة'},
        {'key': 'c', 'value': 'تقييم الأدلة قبل الحكم'},
        {'key': 'd', 'value': 'الاعتماد على الرأي الشخصي فقط'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'التفكير النقدي',
    },
    {
      '_id': 'extra_015',
      'questionText': 'ما الفرق بين الرأي والحقيقة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'لا فرق بينهما'},
        {
          'key': 'b',
          'value': 'الحقيقة قابلة للتحقق والإثبات، بينما الرأي تقدير شخصي'
        },
        {'key': 'c', 'value': 'الرأي دائماً صحيح'},
        {'key': 'd', 'value': 'الحقيقة تتغير بتغير الأشخاص'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'التفكير النقدي',
    },
    {
      '_id': 'extra_016',
      'questionText': 'من هو مخترع الهاتف؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'توماس إديسون'},
        {'key': 'b', 'value': 'ألكسندر غراهام بيل'},
        {'key': 'c', 'value': 'نيكولا تسلا'},
        {'key': 'd', 'value': 'غوليلمو ماركوني'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الذكاء العام',
    },
    {
      '_id': 'extra_017',
      'questionText': 'كم عدد أيام السنة الكبيسة؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '365'},
        {'key': 'b', 'value': '366'},
        {'key': 'c', 'value': '364'},
        {'key': 'd', 'value': '367'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الذكاء العام',
    },
    {
      '_id': 'extra_018',
      'questionText': 'ما هو أسرع حيوان بري في العالم؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الأسد'},
        {'key': 'b', 'value': 'الفهد'},
        {'key': 'c', 'value': 'الحصان'},
        {'key': 'd', 'value': 'الغزال'},
      ],
      'correctAnswer': 'b',
      'difficulty': 1,
      'subject': 'الذكاء العام',
    },
    {
      '_id': 'extra_019',
      'questionText': 'كم عدد نجوم العلم الأمريكي؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': '48'},
        {'key': 'b', 'value': '50'},
        {'key': 'c', 'value': '52'},
        {'key': 'd', 'value': '51'},
      ],
      'correctAnswer': 'b',
      'difficulty': 2,
      'subject': 'الذكاء العام',
    },
    {
      '_id': 'extra_020',
      'questionText':
          'ما هي اللغة الأكثر انتشاراً في العالم من حيث عدد المتحدثين الأصليين؟',
      'questionType': 'mcq',
      'options': [
        {'key': 'a', 'value': 'الإنجليزية'},
        {'key': 'b', 'value': 'الإسبانية'},
        {'key': 'c', 'value': 'الصينية الماندرين'},
        {'key': 'd', 'value': 'العربية'},
      ],
      'correctAnswer': 'c',
      'difficulty': 2,
      'subject': 'الذكاء العام',
    },
  ];

  /// Get questions filtered by subject name.
  static List<Map<String, dynamic>> bySubject(String subject) =>
      all.where((q) => q['subject'] == subject).toList();
}
