include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'lib/generated/**'
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true

linter:
  rules:
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    throw_in_finally: true
    unnecessary_statements: true
